MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "./"
  DOMAIN_ADAPTATION_ON: True
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 15
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 256
    NMS: 0.3
  DA_HEADS:
    DA_IMG_GRL_WEIGHT: 0.1
    DA_INS_GRL_WEIGHT: 0.1
DATALOADER:
  SIZE_DIVISIBILITY: 32
DATASETS:
  TRAIN: ("label0_SeaShips_SMD_voc",)
  SOURCE_TRAIN: ("label0_SeaShips_SMD_voc",)
  TARGET_TRAIN: ("unlabel0_SeaShips_SMD_voc",)
  TEST: ("test1283_SeaShips_SMD_voc",)
INPUT:
  MIN_SIZE_TRAIN: (600,)
  MAX_SIZE_TRAIN: 1200
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1200
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  STEPS: (50000,)
  MAX_ITER: 20000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 1
